# Generated by Django 3.1.7 on 2021-04-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image of the slide')),
                ('title', models.TextField(verbose_name='the main title')),
                ('title2', models.TextField(verbose_name='the second title')),
                ('link', models.TextField(verbose_name='the link to the object')),
            ],
        ),
    ]
